### ISSUE TITLE
pathway_table misssing

### ISSUE THREAD

**Issue by pollicipes** [anttonalberdi/DAMMA#7]
Hi Antton!

I am trying to test DAMMA with my own data, but I can't find the `pathway_table`, which goes in the `functions` argument in the `MCI_table` function.  In the `README.md` it says it is included, but after loading the package I get the error:

`> head(DAMMA::pathway_table)`

> Error: 'pathway_table' is not an exported object from 'namespace:DAMMA

I am not sure if I have to generate my own `functions` object, but I would like to be able to see the `pathway_table`, so I know the format.

Also, I checked on the help, but it says it is provided by GAMMA:

`functions | Table containing definitions and metadata of metabolic functions (provided by GAMMA)`

Is this an typo, and you mean "DAMMA"? 

Any help appreciated!

Eskerrik asko!
Juan

**Comment by anttonalberdi** [comment]
Hi Juan. The pathway_table object is loaded when the package is loaded. try `head(pathway_table)`
If it does not give you the overview of the table, then reinstall DAMMA to the newest version, and it should work.

**Comment by pollicipes** [comment]
Kaixo Antton,

I had previously also tried `head(pathway_table)`, but it didn't work. Now I reinstalled DAMMA to the last version and now it seems to work.  :)

Thank you so much!
Best,
Juan
