### ISSUE TITLE
MCI_table not generated; error damma() function

### ISSUE THREAD

**Issue by pollicipes** [anttonalberdi/DAMMA#8]
Hi again, Antton!

I am trying to run the example data, but I get the following error:

![Screenshot 2022-09-27 at 11 08 25](https://user-images.githubusercontent.com/35963280/192484927-6999b021-0e59-4d95-901a-6569aec1341f.png)

I have been "gutting" the code a bit, and this error first comes from the `create_step_matrix()` function, line 36 in the script in this repo. In there, it is trying to compare a level to number, so it complains...

Also, I don't know if that can be related, but on the `compute_MCI()`, when you split the EC codes (line 18), there are a lot of parentheses, commas, whitespaces, etc. that get included in the `def_decomp` variable, as if they were EC codes...

I tried to fix all this in my code, but I couldn't solve it...

Do you have any suggestions?

Thanks!
Juan

**Comment by anttonalberdi** [comment]
Weird, I don't get that error myself. I guess it might be related to some hidden dependency or conflict with another package that I have overlooked.

**Comment by pollicipes** [comment]
Hi Antton,

I think it is a problem of the R version. I have tried it with the 4.1.1 and it works. It might not work well with some previous ones (v3.5)

Cheers!
Juan
